### ISSUE TITLE
Grid labels in all 4 sides

### ISSUE THREAD

**Issue by andresperezl** [otfbm/maps#60]
With large maps is usually pretty hard to know precisely which grid position you want to move or target if you are too far to the right or too far down, as you need to track back to the opposite side to know where you want to move.

Having the labelling on the four sides should help with that problem.

**Comment by thurstyyyy** [comment]
Honestly? I’ve never once had this issue.

**Comment by patpluspun** [comment]
Thanks for your input @andresperezl but our issue queue is in another [repo](https://github.com/oftbm/issues).  And this has already been requested: https://github.com/otfbm/issues/issues/45

**Comment by andresperezl** [comment]
Thank you @patpluspun, I will close this then
